# Generated by Django 4.2.1 on 2023-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treevkusa', '0002_foodmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='image_path',
            field=models.CharField(default=str, max_length=300),
            preserve_default=False,
        ),
    ]
