# Generated by Django 4.2.1 on 2023-05-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treevkusa', '0003_foodmenu_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='type',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
