# Generated by Django 4.2.1 on 2023-05-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treevkusa', '0004_foodmenu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=str, max_length=40),
            preserve_default=False,
        ),
    ]
